CREATE TABLE IF NOT EXISTS lands (
  scryfall_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type_line TEXT NOT NULL,
  image_url TEXT NOT NULL,
  votes INTEGER NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vote_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scryfall_id TEXT REFERENCES lands(scryfall_id),
  client_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
